js/acf/fields/markdown-editor.js
src/ACF/MarkdownEditor.php
src/Models/ACF/Composite/CompositeFieldGroup.php
src/Models/ACF/Composite/TeaserFieldGroup.php

- Fixed a bug where newly inserted ACF markdown fields would not be
loaded correctly.

BUGFIX: Refactored ACF markdown field javascript

---

js/acf/fields/markdown-editor.js
src/Commands/Composites.php
src/Helpers/CollectionHelper.php
src/Models/ACF/Composite/MetaFieldGroup.php
src/Models/ACF/Composite/TaxonomyFieldGroup.php
src/Models/WpTaxonomy.php

- Fixed bug in markdown editor causing toolbar to use default icons
- Fixed bug in teasers not being saved
- Added automatic generation of custom taxonomy field keys

Added code to import tags with vocabularies to custom taxonomies

---

contenthub-editor.php
src/Commands/CmdManager.php
src/Commands/Taxonomy/BaseTaxonomyImporter.php
src/Commands/Taxonomy/Categories.php
src/Commands/Taxonomy/Tags.php
src/Commands/Taxonomy/Vocabularies.php
src/Helpers/PolylangConfig.php

- Fixed various code that was generating nottices

Added class to tell polylang to translate our custom post type and custom taxonomies

---

src/Commands/Taxonomy/BaseTaxonomyImporter.php
src/Commands/Taxonomy/Helpers/WpTerm.php

- Removed unused import of seo text and image url

Internal property on imported terms are now saved locally

---

src/Models/WpComposite.php
src/Repositories/Scaphold/CompositeRepository.php
src/Scaphold/Queries.php

- This is WIP only so we get a contenthub_id for purchase manager

Added code to save composites to scaphold on save_post

---

src/ACF/MarkdownEditor.php
src/Commands/Composites.php

- Disabled on_save hook on composite import to avoid calling Cxense and
Content Hub

Added code to allow slashes in acf markdown-editor fields

---

src/Commands/Composites.php
src/Models/WpComposite.php
src/Repositories/Contracts/Scaphold/CategoryContract.php
src/Repositories/Scaphold/CategoryRepository.php
src/Scaphold/Queries.php

- Fixed typo in composites import
- Added map_all function to map WpComposites

Added Scaphold/CategoryResository

---

contenthub-editor.php
src/Models/ACF/Composite/CompositeFieldGroup.php

Add download btn text for files.

FORD-107/add-file-btn-txt

---

src/Models/WpComposite.php

- Removed no longer needed custom rewrite rule

BUGFIX: Changed the plugin to set proper permalink structure

---

README.md
src/Models/WpComposite.php

Added on slug change hook to plugin

---

src/Models/ACF/Composite/CompositeFieldGroup.php

WILL-367/add checkbox

---

contenthub-editor.php
includes/composer.json
includes/composer.lock
includes/vendor/composer/ClassLoader.php
includes/vendor/composer/autoload_files.php
includes/vendor/composer/autoload_psr4.php
includes/vendor/composer/autoload_static.php
includes/vendor/composer/installed.json
js/acf/fields/composite-validation.js
src/Helpers/CompositeHelper.php
src/Models/ACF/Composite/CompositeFieldGroup.php

- Move video logic from vue-base to contenthub. It's tightly coupled to the composite.
- Added video-helper php lib as a dependency.

Will-367/refactor-context

---

src/Commands/WaContent.php
src/Models/WpAttachment.php

- Fixed wrong wa id being saved

Fixed bug when importing .psd images

---

src/Models/WpComposite.php

WIP. This should not be merged yet.

fix-permalinks

---

src/Helpers/SlugHelper.php

- Fixed bug in imported category slugs where special chars were not being stripped

WILL-667: Fixed bug in category slug import

---

contenthub-editor.php
js/acf/fields/markdown-editor.js
src/Models/ACF/Composite/CompositeFieldGroup.php

- Added new JS for the Markdown editor
- Updated Text item to support new markdown editor configs
- Updated Gallery item to support inline gallery display hint.

WILL-158 - Easy tables

---

.gitignore
src/Models/WpAttachment.php
src/Models/WpComposite.php

Removed caption rich markdown field!

---

.gitignore
src/Models/WpAttachment.php
src/Models/WpComposite.php

Reverts BenjaminMedia/wp-contenthub-editor#183

Revert "Removed caption rich markdown field!"

---

contenthub-editor.php
src/Models/ACF/Composite/CompositeFieldGroup.php

+ changed author key to be const

IVD-403/BUGFIX changed author key to be const

---

contenthub-editor.php

IVD-401/added audio fields to meta

---

composer.lock
contenthub-editor.php
src/Helpers/AcfName.php
src/Models/ACF/Page/Widgets/TeaserList.php

IVD-382 - Teaser List

---

contenthub-editor.php
js/acf/fields/image-hotspot-coordinates.js
js/acf/fields/markdown-editor.js

- Fixes issue where the markdown field was not loaded
- Fixes issue where deleting a hotspot row not actually deleting the hotspots

IVD-282/BUGFIX: Initial load of Image hotpsot widgets

---

contenthub-editor.php
src/Commands/WaContent.php
src/Repositories/WhiteAlbum/ContentRepository.php

- Added better handling of unknown article types

WILL-911/BUGFIX: WA import issue in translations

---

contenthub-editor.php
src/Helpers/AcfName.php
src/Models/ACF/Page/Widgets/SeoText.php
src/Models/WpPage.php

IVD-398/FEATURE added Seo Text page widget

---

contenthub-editor.php
src/Helpers/AcfName.php
src/Models/ACF/Page/BaseWidget.php
src/Models/ACF/Page/Widgets/BannerPlacement.php
src/Models/ACF/Page/Widgets/FeaturedContent.php
src/Models/ACF/Page/Widgets/Newsletter.php
src/Models/ACF/Page/Widgets/SeoText.php
src/Models/ACF/Page/Widgets/TeaserList.php
src/Models/ACF/WidgetContract.php
src/Models/WpPage.php

- Newsletter widget
- Banner Placement widget

IVD-398 - Added simple page widgets

---

contenthub-editor.php
src/Commands/WaContent.php
src/Commands/WaRedirectResolver.php
src/Repositories/WhiteAlbum/ContentRepository.php

- Added option to skip already imported articles
- Added option to start import from specific page

WILL-911/FEATURE: improved import script

---

contenthub-editor.php
js/acf/fields/image-hotspot-coordinates.js

- Fixes a bug in newly created hotspot images where the input of the hotspot was not being updated correctly

IVD-924/BUGFIX: Hotspot image image validation

---

composer.lock
contenthub-editor.php
src/Models/ACF/Composite/CompositeContentFieldGroup.php

Adding option to make paragraph lists collapsible
Adding display format 'Parallax' to galleries

IVD-428 - Collapsible paragraph lists

---

contenthub-editor.php
src/Commands/WaContent.php
src/Models/WpComposite.php

- Added extra post meta to save WA source for later use

IVD-59/BUGFIX: Vimeo was being mapped as video23

---

contenthub-editor.php
src/Models/ACF/Composite/CompositeContentFieldGroup.php

Renaming chapter display format from `inline` to `chapter` to make sense.

Bugfix - Lead Paragraph chapters

---

contenthub-editor.php
src/Helpers/CompositeHelper.php

We need to add the postId to make tests succeed.

Bugfix - Fix for tests

---

contenthub-editor.php
src/Helpers/SortBy.php

Making protected methods public to be used in ContentController in Willow Base Theme

IVD-428 - Get Popular Articles

---

contenthub-editor.php
src/Helpers/SortBy.php

- Solves issue with cxense generated content in composite helper

BUGFIX: bug where wrong composite id's fetched

---

composer.lock
contenthub-editor.php
src/Models/ACF/Page/Meta/Sitemap.php
src/Models/WpPage.php

Adding Page Meta field group, that will contain an option to exclude pages from sitemaps.

IVD-466 - Excluding pages from sitemap

---

composer.lock
contenthub-editor.php
js/acf/fields/page-validation.js
src/ACF/MarkdownEditor.php
src/Models/ACF/Page/Widgets/TeaserList.php

Adding option to mark Teaser List as paginated.
Adding JavaScript to validate that only one teaserlist is marked as paginated.

IVD-456 - Pagination on Section Pages

---

contenthub-editor.php
src/Commands/CmdManager.php
src/Helpers/AcfName.php
src/Models/ACF/Page/Widgets/CommercialSpot.php
src/Models/WpPage.php

Ivd 526/added commercial spot

---

contenthub-editor.php
src/Helpers/SortBy.php

Updating SortBy helper to return pagination data.

IVD-456 - Teaser List Pagination

---

contenthub-editor.php
src/Models/ACF/Page/Widgets/CommercialSpot.php

-  add label to commercial spot

IVD-526/feature add label to commercial spot

---

.gitignore
composer.lock
contenthub-editor.php
src/Helpers/TermImportHelper.php

Whenever a category is updated causing its url to change, a redirect will be created for that category and all subcategories.

WILL-910 - Creating category page redirects on changes

---

contenthub-editor.php
src/Helpers/TermImportHelper.php

Bugfix for tag and category page redirects not being created when names are updated in sitemanager.

WILL-910 - Tag and category redirects

---

composer.lock
contenthub-editor.php
css/admin.css
js/acf/fields/markdown-editor.js
src/Commands/Attachments.php
src/Commands/CmdManager.php
src/ContenthubEditor.php
src/Models/ACF/Attachment/AttachmentFieldGroup.php
src/Models/WpAttachment.php

Hiding the default attachment caption with css and adding a new caption with ACF that supports markdown.
Also adding a script that copies captions from post_excerpt to the new ACF field.

IVD-588 - Attachment captions

---

contenthub-editor.php
src/Models/ACF/Composite/MetaFieldGroup.php

- add no index options to composites

IVD-622/add no index options to composites

---

contenthub-editor.php
src/Helpers/AcfName.php
src/Models/ACF/Page/Widgets/FeaturedContent.php

- add series teaser widget to frontpage

Ivd 646/add series teaser widget to frontpage

---

contenthub-editor.php
src/Http/Api/UpdateEndpointController.php

Manually deleting cached hierarchy after updates.

WILL-867 - Fixing broken category structure

---

contenthub-editor.php
src/Http/Api/UpdateEndpointController.php

Making sure the Polylang constant PLL_ADMIN is set to true, when updating categories from SiteManager.

WILL-867 - Category hierachy issue

---

contenthub-editor.php
src/Helpers/AcfName.php
src/Models/ACF/Page/Widgets/CommercialSpot.php

- add magazine teaser widget to frontpage
IVD-652

IVD-652/add magazine teaser widget to frontpage

---

contenthub-editor.php
src/Helpers/CompositeHelper.php

- Added check if article is part of multiple stories. Presents warning to user with a link to the other story, if article is part of another story.
- Bumped version.

- Added check if article is part of multiple stories.

---

contenthub-editor.php
src/Helpers/CompositeHelper.php

Checking if both articles are of kind story, to be able to use articles as subcontent on only 1 post with kind story but multiple times on post with other kind.

Checking if both articles are of kind story.

---

contenthub-editor.php
js/acf/fields/markdown-editor.js

Unwrapping value in encodeURI to prevent encoding already encoded characters.

Unwrapping value in encodeURI

---

contenthub-editor.php
src/Models/ACF/Composite/MagazineFieldGroup.php

- Added issue 19 to range in MagazineFieldGroup.

---

contenthub-editor.php
src/Models/Partials/EstimatedReadingTime.php

EstimatedReadingTime crashed on composites with empty content array

BUGFIX: EstimatedReadingTime

---

contenthub-editor.php
src/Commands/WaContent.php

Fixes an issue where translations from  WA were not imported correctly

HIS-27/BUGFIX: Missing translations

---

contenthub-editor.php
src/Commands/Taxonomy/Helpers/WpTerm.php
src/Helpers/TermImportHelper.php
src/Repositories/SiteManager/VocabularyRepository.php

- Added support for importing category and tag slugs from site manager
- Fixed bug in vocabulary import

HIS-39/term slug import

---

contenthub-editor.php
src/Helpers/TermImportHelper.php

Fixes an issue where the translations would not sync because the translation id was not returned.

WILL-1423/bugfix-translations-sync

---

contenthub-editor.php
src/Helpers/CompositeHelper.php

- Added check to only set story parent if the current article is of kind story.
- Refactored a bit, so we always clear the parent story if it's not a valid story. This way the parent story will now be removed if editors change kind from story to something else.

WILL-1465/check if article is of kind story.

---

src/Commands/Taxonomy/BaseTaxonomyImporter.php
src/Commands/Taxonomy/Vocabularies.php

Fixes an issue where import commands from sitemanager would run one time for each site, this is not necesssary since the content is translated

Fix SM import loops

---

composer.lock
contenthub-editor.php
src/Helpers/AcfName.php
src/Models/ACF/Composite/MetaFieldGroup.php
src/Models/ACF/Page/Widgets/QuoteTeaser.php
src/Models/WpPage.php

Adding Quote Teaser to pages, allowing editors to have large text linking to either a composite or a link.
Adding Link Label and Link to Composite Commercial meta, to allow commercials to link to the advertiser.

WILL-1623 - Adding Quote Teaser and links to composite commercial meta

---

contenthub-editor.php
src/Commands/WaContent.php

Adds support for importing shell articles from WA

WILL-1684/feature: shell articles

---

contenthub-editor.php
src/Commands/WaContent.php

Alters import of Wa gallery articles to become a widget rather than inline text item + image widgets

WILL-1621/feature-gallery-import

---

composer.json
composer.lock
contenthub-editor.php
src/Commands/CmdManager.php
src/Commands/Taxonomy/Helpers/WpTerm.php
src/Commands/WaContent.php
src/Commands/WaPanel.php
src/Helpers/AcfName.php
src/Helpers/HtmlToMarkdown.php
src/Helpers/SortBy.php
src/Models/ACF/Page/BaseWidget.php
src/Models/ACF/Page/Widgets/SeoText.php
src/Repositories/WhiteAlbum/PanelRepository.php

- New command to import wa panel pages (for categories only)
- Change HTML to makdown service to using package rather than making a HTTP request
- Add skip support to sort by options when selecting by taxonomy

Will 1744/panel import

---

contenthub-editor.php
src/Commands/WaPanel.php

- Bugfix crash in edge case
- Adds missing locale parameter

WILL-1744/bugfix-import-crash

---

contenthub-editor.php
src/Commands/WaContent.php

Fixes an issue where the video23 account was not being imported

WILL-1621/bugfix-video23-import

---

contenthub-editor.php
src/Commands/WaContent.php
src/Helpers/HtmlToMarkdown.php

Fixes an issue were some headings were being imported as ordered llists

WILL-1806/fix-headings-import

---

codeception.dist.yml
composer.json
composer.lock
contenthub-editor.php
src/ACF/CustomRelationship.php
src/ACF/MarkdownEditor.php
src/Database/DB.php
src/Helpers/FeatureTimeField.php
src/Helpers/HtmlToMarkdown.php
src/Helpers/PolylangConfig.php
src/Models/WpComposite.php
src/Models/WpUserProfile.php
src/Repositories/WhiteAlbum/ContentRepository.php
src/Repositories/WhiteAlbum/ImageRepository.php
src/Repositories/WhiteAlbum/PanelRepository.php

update willow-mu-plugins to version ^2.0 so we can upgrade wp-bonnier-cache with this afterwards.

Upgrade acf to 5.12.2
